In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_datareader import data, wb
import datetime
import pickle
import os
from scipy import fftpack
import seaborn as sns
from matplotlib.font_manager import FontProperties
import pandas.io.data as web

In [10]:
def load_google_stock_data(code, start, end):
    
    try:
        df=web.DataReader(code, 'google', start, end)
    except Exception as e:
        return pd.DataFrame()
    
    return df

In [11]:
# test
s=datetime.datetime(2011, 1, 1)
e=datetime.datetime(2016, 7, 1)
load_google_stock_data('KRX:000070', s, e)

                Open      High       Low     Close  Volume
Date
2011-01-03   70300.0   70900.0   69700.0   70700.0   23950
2011-01-04   70600.0   71700.0   70200.0   71700.0   26243
2011-01-05   71700.0   72000.0   70600.0   71600.0   24867
2011-01-06   71600.0   75500.0   71400.0   75100.0   73496
2011-01-07   75200.0   75400.0   72500.0   73200.0   82224
2011-01-10   72500.0   72600.0   71300.0   72000.0   31475
2011-01-11   72000.0   74600.0   72000.0   74600.0   40970
2011-01-12   74700.0   77000.0   74000.0   75900.0   46585
2011-01-13   75100.0   75900.0   74200.0   74200.0   27325
2011-01-14   73900.0   74900.0   72500.0   74700.0   17137
2011-01-17   73300.0   74300.0   72000.0   72500.0   25919
2011-01-18   72500.0   73000.0   70700.0   72000.0   39224
2011-01-19   72100.0   72200.0   71200.0   71500.0   17294
2011-01-20   70800.0   71900.0   70100.0   70800.0   32331
2011-01-21   71500.0   71500.0   69000.0   69000.0   23849
2011-01-24   67000.0   69800.0   67000.0   68400.0   27114
2011-01-25   68700.0   70000.0   68400.0   68400.0   34013
2011-01-26   68500.0   69300.0   67600.0   68400.0   38579
2011-01-27   68700.0   70400.0   68200.0   69900.0   36548
2011-01-28   69200.0   69900.0   68000.0   68000.0   30870
2011-01-31   67800.0   67800.0   64000.0   64000.0   42538
2011-02-01   64500.0   65700.0   64100.0   65000.0   20166
2011-02-07   65800.0   66300.0   63700.0   64900.0   29188
2011-02-08   64900.0   64900.0   63700.0   64400.0   23207
2011-02-09   64400.0   66400.0   64400.0   65900.0   33698
2011-02-10   66200.0   69600.0   65200.0   67200.0  108143
2011-02-11   67900.0   68900.0   65100.0   65100.0   34342
2011-02-14   65200.0   65500.0   63700.0   64500.0   23038
2011-02-15   64000.0   64500.0   61400.0   61600.0   57813
2011-02-16   61000.0   63900.0   60600.0   62500.0   46746
...              ...       ...       ...       ...     ...
2016-05-20  158500.0  158500.0  155000.0  155500.0    9374
2016-05-23  154000.0  154500.0  150500.0  151000.0   19424
2016-05-24  150000.0  152000.0  142500.0  143000.0   33383
2016-05-25  145000.0  151500.0  143500.0  149500.0   25298
2016-05-26  149000.0  149500.0  142500.0  144000.0   18939
2016-05-27  144000.0  146000.0  143500.0  144500.0    8197
2016-05-30  144500.0  146000.0  142000.0  145000.0    8513
2016-05-31  144000.0  149000.0  144000.0  147000.0   12299
2016-06-01  146000.0  150500.0  145500.0  150000.0   14226
2016-06-02  148500.0  150000.0  147000.0  148500.0   11474
2016-06-03  148500.0  149500.0  146000.0  149000.0   10918
2016-06-07  151000.0  158000.0  149500.0  156000.0   25402
2016-06-08  154000.0  158000.0  153500.0  156500.0   12442
2016-06-09  155500.0  159000.0  154500.0  159000.0   19514
2016-06-10  158500.0  159000.0  156500.0  159000.0   13954
2016-06-13  158500.0  161000.0  154500.0  156500.0   18908
2016-06-14  156000.0  158000.0  153000.0  153000.0   15881
2016-06-15  153000.0  155500.0  153000.0  153000.0    7294
2016-06-16  153000.0  154500.0  149000.0  150500.0    8098
2016-06-17  150500.0  152500.0  148000.0  149500.0    9613
2016-06-20  152000.0  154000.0  151000.0  153500.0    8473
2016-06-21  152000.0  154500.0  151500.0  152500.0    4936
2016-06-22  153500.0  154000.0  151000.0  153500.0    7397
2016-06-23  152500.0  154000.0  151000.0  151500.0    6750
2016-06-24  152500.0  153500.0  142000.0  147500.0   27517
2016-06-27  147000.0  150000.0  144000.0  149000.0   11956
2016-06-28  148500.0  151000.0  146000.0  150500.0    9606
2016-06-29  150000.0  152000.0  148000.0  148000.0   20224
2016-06-30  148500.0  150000.0  146500.0  146500.0   12481
2016-07-01  147000.0  148500.0  145000.0  145500.0   31880

[1330 rows x 5 columns]